project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "data-science-blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/in/yonassgebre
format:
  html:
    theme:
      - cosmo
      - cerulean
      - lux
    css: styles.css


